import zoom

ZOOM_ACCOUNT_ID="mQ6z7LM9R4yuzZ64Iju6rA"
ZOOM_CLIENT_ID="gnf5YJx2S1KGyNXCrDqmPQ"
ZOOM_CLIENT_SECRET="4p7goBVRIQxBzmEZL1580UlbucHI8NxW"
x = zoom.Zoom(ZOOM_ACCOUNT_ID, ZOOM_CLIENT_ID, ZOOM_CLIENT_SECRET)
print(x.meeting_list())
